resources:
- repo: self

pool:
    name: Default

trigger:
  branches:
    include:
    - master
#    exclude:
#    - master
  paths:
    include:
    - oozie-repository/coordinators/projectname/appname1 ## '*'  same as '/' for the repository root
    exclude:
    - 'docs/*' # same as 'docs/'

steps:

- script: |
    echo '##vso[task.setvariable variable=pig]$(pig)'
    echo '##vso[task.setvariable variable=hive]$(hive)'
    echo '##vso[task.setvariable variable=shell]$(shell)'
    echo '##vso[task.setvariable variable=gavr]$(gavr)'
    echo '##vso[task.setvariable variable=app_name]appname1'
    echo '##vso[task.setvariable variable=coordinator_parent_workflow_job_properties]oozie-repository/workflows/projectname/appname1'
    echo '##vso[task.setvariable variable=coordinator_job_properties]oozie-repository/coordinators/projectname/appname1'
    echo "I am `whoami` and my workspace is: "
    pwd
 

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: '/usr/bin/python coordinator_json_parser.py build'

- task: PublishPipelineArtifact@0
  inputs:
    artifactName: 'CI-CD'
    targetPath: