resources:
- repo: self

steps:

- script: |
    echo '##vso[task.setvariable variable=pig]$(pig)'
    echo '##vso[task.setvariable variable=hive]$(hive)'
    echo '##vso[task.setvariable variable=shell]$(shell)'
    echo '##vso[task.setvariable variable=gavr]$(gavr)'



# An environment variable called `Helix Genome Variables` has been added to all downstream steps
- bash: |
    echo PIG environment variable is $PIG
    echo HIVE environment variable is $HIVE
    echo Third environment variable is $SHELL
    ls -ltrha
    whoami
    python --version
    printenv
    

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'python coordinator_json_parser.py build'
