resources:
- repo: self

steps:

- script: |
    echo '##vso[task.setvariable variable=pig]$(pig)'
    echo '##vso[task.setvariable variable=hive]$(hive)'
    echo '##vso[task.setvariable variable=shell]$(shell)'
    echo '##vso[task.setvariable variable=gavr]$(gavr)'

# Retrieves the specified version of Python from the tool cache. Optionally add it to PATH.
- task: UsePythonVersion@0
  inputs:
    versionSpec: '2.7.16' 
    addToPath: true 
    #architecture: 'x64' # Options: x86, x64 (this argument applies only on Windows agents)
 
# An environment variable called `Helix Genome Variables` has been added to all downstream steps
- bash: |
    echo PIG environment variable is $PIG
    echo HIVE environment variable is $HIVE
    echo Third environment variable is $SHELL
    whoami
    python --version
    

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'python coordinator_json_parser.py build'
